### ISSUE TITLE
Dark Variant Applications on Light Variants Display Old Titlebar Button 

### ISSUE THREAD

**Issue by jws141** [Muqtxdir/yaru-blue#1]
Awesome theme and love the new titlebar buttons from master.  Any application that is dark by default i.e. Eye Of Gnome or selecting a dark variant option while using the light or standard version, the old blue buttons are there.  Thanks.

![Screenshot from 2020-07-24 08-40-53](https://user-images.githubusercontent.com/68739609/88392359-d8d0d600-cd89-11ea-99a6-66baf75438ac.png)

![Screenshot from 2020-07-24 08-47-43](https://user-images.githubusercontent.com/68739609/88392749-8d6af780-cd8a-11ea-847d-79af54257358.png)

**Comment by Muqtxdir** [comment]
Hi @jws141,

Glad that you are enjoying the theme!
Can you share the screenshot?

**Comment by Muqtxdir** [comment]
Sorry for asking silly-stuff

But can you tell me what apps are affected by this problem so that I can try a look at it ? ( I see lollypop, eog in screenshots)
Is the terminal and nautilus also affected?

**Comment by jws141** [comment]
No worries.  Terminal is good.  It's just apps that are dark by default or if you select "use dark variant" while using the light or standard theme.  When using the Yaru-blue-dark theme everything is perfect.  Hope that clarifies for you.  Thanks again.

**Comment by Muqtxdir** [comment]
Thanks for the clarification
Ok, will look into this

**Comment by Muqtxdir** [comment]
Hi @jws141,

Sorry I forgot to add `gtk-dark.css` for **Yaru-blue** and **Yaru-blue-light** (*my bad*)

Anyway, I've just pushed an update to `master` that adds `gtk-dark.css` to the affected themes
Please check-out the theme from `master` and tell whether this fixes it or not?

**Comment by jws141** [comment]
Yes, perfect!.   Thanks for the quick fix and keep up the great work.

**Comment by Muqtxdir** [comment]
Hey do you mind putting the screenshots again?
And thanks for reporting this issue @jws141

**Comment by jws141** [comment]
Sure the original screenshots or ones with the fix? Np @Muqtxdir

**Comment by Muqtxdir** [comment]
> Sure the original screenshots or ones with the fix? Np @Muqtxdir

The fixed-ones

**Comment by jws141** [comment]
![Screenshot from 2020-07-24 11-24-54](https://user-images.githubusercontent.com/68739609/88407759-95ce2d00-cda0-11ea-8a33-f7a2007a03be.png)
![Screenshot from 2020-07-24 11-25-40](https://user-images.githubusercontent.com/68739609/88407766-9797f080-cda0-11ea-9ffd-1e47608d5e19.png)
![Screenshot from 2020-07-24 11-26-14](https://user-images.githubusercontent.com/68739609/88407770-98c91d80-cda0-11ea-8777-3045fe5ee795.png)

**Comment by Muqtxdir** [comment]
Hi @jws141 

From your screenshots, I also noticed that in **Lollypop** the web-icon is shown as missing
I fixed this in all icon-themes
Check and apply the theme again (*so sorry, I know this is frustrating*)
Here is the comparision
## Before:
![lollypop-web](https://user-images.githubusercontent.com/54065734/88425817-ac5e9d80-ce0d-11ea-9126-73185dee44c3.jpg)
## After:
![loli](https://user-images.githubusercontent.com/54065734/88426083-22630480-ce0e-11ea-9dfd-68fb36fa5a6c.png)

Thanks!

**Comment by jws141** [comment]
Yep works great. I did get a meson build error and had to delete the  Yaru-blue* icons from /usr/share/icons then reinstalled and the icon was changed. Thanks!

![Screenshot from 2020-07-24 20-10-53](https://user-images.githubusercontent.com/68739609/88444199-fe8dc780-cde9-11ea-9659-31476e0f8bd1.png)
